title: "Patricia KOTO"
description: "Data Analyst | Statisticienne | Économiste du développement"
theme: jekyll-theme-minimal
lang: fr
show_downloads: false
baseurl: "/portfolio-Patricia-Koto"
logo: assets/img/photo.jpg